doc fix
s-a-nersisyan/ExhauFS pull request #12
Opened 2021-08-05 19:01 UTC by NovosadVictor

2021-08-05 19:19 UTC, s-a-nersisyan requested changes

2021-08-05 19:19 UTC, s-a-nersisyan commented on tutorial/colorectal_cancer/config_for_build_regressors.json
> +	"preprocessor": null,
FIXME

2021-08-05 19:19 UTC, s-a-nersisyan commented on tutorial/colorectal_cancer/config_for_estimate_regressors.json
> +	"preprocessor": null,
FIXME

2021-08-05 19:19 UTC, s-a-nersisyan commented on tutorial/colorectal_cancer/n_k.csv
> -25,20,1.5562555293440818
Perhaps leave running time estimation there? User will see how it looks like

2021-08-06 12:51 UTC, NovosadVictor commented on tutorial/colorectal_cancer/config_for_build_regressors.json
> +	"preprocessor": null,
+

2021-08-06 12:51 UTC, NovosadVictor commented on tutorial/colorectal_cancer/config_for_estimate_regressors.json
> +	"preprocessor": null,
+

2021-08-06 12:51 UTC, NovosadVictor commented on tutorial/colorectal_cancer/n_k.csv
> -25,20,1.5562555293440818
tutorial/colorectal_cancer/results_estimate_regressors/estimated_times.csv

Вот тут в результатах полная таблица

2021-08-06 13:49 UTC, s-a-nersisyan approved these changes

2021-08-06 13:49 UTC, merged